# Generated by Django 3.2.7 on 2021-10-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=120)),
                ('tag', models.CharField(max_length=120)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speach.text')),
            ],
        ),
    ]
