# Generated by Django 3.2.7 on 2021-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtext',
            name='text',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='detailtext',
            name='pos',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='detailtext',
            name='tag',
            field=models.CharField(default='', max_length=120),
        ),
    ]
